# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\myfiles\pythonproject\ReptileDemo\spider\OAIndex.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1209, 809)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        Form.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(30, 20, 30, 20)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.userinfo = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userinfo.sizePolicy().hasHeightForWidth())
        self.userinfo.setSizePolicy(sizePolicy)
        self.userinfo.setObjectName("userinfo")
        self.horizontalLayout_3.addWidget(self.userinfo)
        self.loginout = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginout.sizePolicy().hasHeightForWidth())
        self.loginout.setSizePolicy(sizePolicy)
        self.loginout.setObjectName("loginout")
        self.horizontalLayout_3.addWidget(self.loginout)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.sys_tips = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sys_tips.sizePolicy().hasHeightForWidth())
        self.sys_tips.setSizePolicy(sizePolicy)
        self.sys_tips.setObjectName("sys_tips")
        self.horizontalLayout_4.addWidget(self.sys_tips)
        self.myReview = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.myReview.sizePolicy().hasHeightForWidth())
        self.myReview.setSizePolicy(sizePolicy)
        self.myReview.setObjectName("myReview")
        self.horizontalLayout_4.addWidget(self.myReview)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.messages = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.messages.sizePolicy().hasHeightForWidth())
        self.messages.setSizePolicy(sizePolicy)
        self.messages.setObjectName("messages")
        self.horizontalLayout.addWidget(self.messages)
        self.showdetails = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showdetails.sizePolicy().hasHeightForWidth())
        self.showdetails.setSizePolicy(sizePolicy)
        self.showdetails.setMinimumSize(QtCore.QSize(20, 0))
        self.showdetails.setMaximumSize(QtCore.QSize(20, 16777215))
        self.showdetails.setText("")
        self.showdetails.setObjectName("showdetails")
        self.horizontalLayout.addWidget(self.showdetails)
        self.horizontalLayout.setStretch(0, 10)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_4.setStretch(0, 6)
        self.horizontalLayout_4.setStretch(1, 6)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setIndent(20)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 2, 1)
        self.gridLayout.setColumnStretch(0, 10)
        self.verticalLayout.addLayout(self.gridLayout)
        self.splitter = QtWidgets.QSplitter(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(1)
        self.splitter.setObjectName("splitter")
        self.toolBox = QtWidgets.QToolBox(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setMaximumSize(QtCore.QSize(180, 16777215))
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 180, 557))
        self.page.setObjectName("page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.toolBox_2 = QtWidgets.QToolBox(self.page)
        self.toolBox_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox_2.sizePolicy().hasHeightForWidth())
        self.toolBox_2.setSizePolicy(sizePolicy)
        self.toolBox_2.setObjectName("toolBox_2")
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setGeometry(QtCore.QRect(0, 0, 162, 491))
        self.page_7.setObjectName("page_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_7)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton = QtWidgets.QPushButton(self.page_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_4.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.page_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_4.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.page_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_4.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.page_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_4.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.page_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_4.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.page_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_4.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.page_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_4.addWidget(self.pushButton_7)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.toolBox_2.addItem(self.page_7, "")
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setGeometry(QtCore.QRect(0, 0, 98, 80))
        self.page_8.setObjectName("page_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_8)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_10 = QtWidgets.QPushButton(self.page_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_6.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.page_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        self.pushButton_11.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_6.addWidget(self.pushButton_11)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.toolBox_2.addItem(self.page_8, "")
        self.verticalLayout_3.addWidget(self.toolBox_2)
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 180, 557))
        self.page_2.setObjectName("page_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.toolBox_3 = QtWidgets.QToolBox(self.page_2)
        self.toolBox_3.setObjectName("toolBox_3")
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setGeometry(QtCore.QRect(0, 0, 162, 509))
        self.page_9.setObjectName("page_9")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page_9)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.pushButton_12 = QtWidgets.QPushButton(self.page_9)
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_9.addWidget(self.pushButton_12)
        self.pushButton_13 = QtWidgets.QPushButton(self.page_9)
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout_9.addWidget(self.pushButton_13)
        self.pushButton_14 = QtWidgets.QPushButton(self.page_9)
        self.pushButton_14.setObjectName("pushButton_14")
        self.verticalLayout_9.addWidget(self.pushButton_14)
        self.pushButton_15 = QtWidgets.QPushButton(self.page_9)
        self.pushButton_15.setObjectName("pushButton_15")
        self.verticalLayout_9.addWidget(self.pushButton_15)
        self.pushButton_16 = QtWidgets.QPushButton(self.page_9)
        self.pushButton_16.setObjectName("pushButton_16")
        self.verticalLayout_9.addWidget(self.pushButton_16)
        self.pushButton_17 = QtWidgets.QPushButton(self.page_9)
        self.pushButton_17.setObjectName("pushButton_17")
        self.verticalLayout_9.addWidget(self.pushButton_17)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem3)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.toolBox_3.addItem(self.page_9, "")
        self.verticalLayout_8.addWidget(self.toolBox_3)
        self.toolBox.addItem(self.page_2, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 180, 557))
        self.page_3.setObjectName("page_3")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.toolBox_4 = QtWidgets.QToolBox(self.page_3)
        self.toolBox_4.setObjectName("toolBox_4")
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setGeometry(QtCore.QRect(0, 0, 162, 509))
        self.page_10.setObjectName("page_10")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.page_10)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.pushButton_18 = QtWidgets.QPushButton(self.page_10)
        self.pushButton_18.setObjectName("pushButton_18")
        self.verticalLayout_12.addWidget(self.pushButton_18)
        self.pushButton_19 = QtWidgets.QPushButton(self.page_10)
        self.pushButton_19.setObjectName("pushButton_19")
        self.verticalLayout_12.addWidget(self.pushButton_19)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem4)
        self.verticalLayout_13.addLayout(self.verticalLayout_12)
        self.toolBox_4.addItem(self.page_10, "")
        self.verticalLayout_11.addWidget(self.toolBox_4)
        self.toolBox.addItem(self.page_3, "")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 180, 557))
        self.page_4.setObjectName("page_4")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.toolBox_5 = QtWidgets.QToolBox(self.page_4)
        self.toolBox_5.setObjectName("toolBox_5")
        self.page_11 = QtWidgets.QWidget()
        self.page_11.setGeometry(QtCore.QRect(0, 0, 162, 509))
        self.page_11.setObjectName("page_11")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.page_11)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.pushButton_20 = QtWidgets.QPushButton(self.page_11)
        self.pushButton_20.setObjectName("pushButton_20")
        self.verticalLayout_15.addWidget(self.pushButton_20)
        self.pushButton_21 = QtWidgets.QPushButton(self.page_11)
        self.pushButton_21.setObjectName("pushButton_21")
        self.verticalLayout_15.addWidget(self.pushButton_21)
        self.verticalLayout_16.addLayout(self.verticalLayout_15)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem5)
        self.toolBox_5.addItem(self.page_11, "")
        self.verticalLayout_14.addWidget(self.toolBox_5)
        self.toolBox.addItem(self.page_4, "")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 180, 557))
        self.page_5.setObjectName("page_5")
        self.toolBox.addItem(self.page_5, "")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 180, 557))
        self.page_6.setObjectName("page_6")
        self.toolBox.addItem(self.page_6, "")
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ReviewTable = QtWidgets.QTableWidget(self.tab)
        self.ReviewTable.setObjectName("ReviewTable")
        self.ReviewTable.setColumnCount(0)
        self.ReviewTable.setRowCount(0)
        self.verticalLayout_2.addWidget(self.ReviewTable)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.splitter)
        self.verticalLayout.setStretch(1, 10)

        self.retranslateUi(Form)
        self.toolBox.setCurrentIndex(5)
        self.toolBox.layout().setSpacing(0)
        self.toolBox_2.setCurrentIndex(0)
        self.toolBox_2.layout().setSpacing(0)
        self.toolBox_3.setCurrentIndex(0)
        self.toolBox_4.setCurrentIndex(0)
        self.toolBox_5.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "首页"))
        self.userinfo.setText(_translate("Form", "user"))
        self.loginout.setText(_translate("Form", "退出"))
        self.sys_tips.setText(_translate("Form", "系统提示"))
        self.myReview.setText(_translate("Form", "我的批阅"))
        self.messages.setText(_translate("Form", "123"))
        self.label.setText(_translate("Form", "Rb管理信息系统"))
        self.pushButton.setText(_translate("Form", "寻呼发布"))
        self.pushButton_2.setText(_translate("Form", "未阅信息"))
        self.pushButton_3.setText(_translate("Form", "已收寻呼"))
        self.pushButton_4.setText(_translate("Form", "已发寻呼"))
        self.pushButton_5.setText(_translate("Form", "保留信息"))
        self.pushButton_6.setText(_translate("Form", "已收历史寻呼"))
        self.pushButton_7.setText(_translate("Form", "已发历史寻呼"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_7), _translate("Form", "网络寻呼"))
        self.pushButton_10.setText(_translate("Form", "排班管理"))
        self.pushButton_11.setText(_translate("Form", "排班分布"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_8), _translate("Form", "IT在线支持"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("Form", "办公协同系统"))
        self.pushButton_12.setText(_translate("Form", "发起流程"))
        self.pushButton_13.setText(_translate("Form", "我的批阅"))
        self.pushButton_14.setText(_translate("Form", "已经批阅"))
        self.pushButton_15.setText(_translate("Form", "我的申请"))
        self.pushButton_16.setText(_translate("Form", "已退回流程"))
        self.pushButton_17.setText(_translate("Form", "流程查询"))
        self.toolBox_3.setItemText(self.toolBox_3.indexOf(self.page_9), _translate("Form", "我的流程"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("Form", "流程审批系统"))
        self.pushButton_18.setText(_translate("Form", "文件地图"))
        self.pushButton_19.setText(_translate("Form", "我的文件"))
        self.toolBox_4.setItemText(self.toolBox_4.indexOf(self.page_10), _translate("Form", "文件管理"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("Form", "文件管理系统"))
        self.pushButton_20.setText(_translate("Form", "信息通报发布"))
        self.pushButton_21.setText(_translate("Form", "信息通报管理"))
        self.toolBox_5.setItemText(self.toolBox_5.indexOf(self.page_11), _translate("Form", "各部门信息通报"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("Form", "信息发布系统"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _translate("Form", "生产辅助系统"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_6), _translate("Form", "工程管理系统"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "我的批阅"))

